### ISSUE TITLE
Error when building stratum

### ISSUE THREAD

**Issue by TheKingKerellos** [mutalisk999/xmrpool#4]
#### System information
elementary OS 7 Horus
Built on Ubuntu 22.04.3 LTS
Linux 6.2.0-26-generic

Monero version: `monerod --version` or commit hash via `git rev-parse --short HEAD` if `master` branch
Monero 'Fluorine Fermi' (v0.18.3.1-release)

Stratum commit hash: `git rev-parse --short HEAD`

OS & Version: Linux

#### Expected behaviour
Expect the stratum to build successfully

#### Actual behaviour
/home/kero/monero-project/xmrpool/hashing/src/hashing.c:19:5: error: too many arguments to function ‘rx_slow_hash’
   19 |     rx_slow_hash(mainheight, seedheight, seedhash, data, length, hash, miners, is_alt);
      |     ^~~~~~~~~~~~

The above arrow is pointing at rx
#### Steps to reproduce the behaviour
Install the packages listed under ubuntu 18.04
install golang like written above
compile monero with shared libs
link monero source
do cmake . then make

#### Backtrace

````
[backtrace]
````

**Comment by mutalisk999** [comment]
thanks for your issue first. 
I am sorry this repo is only support xmr version 0.17 and not support version 0.18 at current. But it will be supported in the future, maybe one month or later.

**Comment by TheKingKerellos** [comment]
@mutalisk999 Thanks for looking into this, I also want you to check out the tutorial and maybe update it so later users are clearer when meeting dependencies as I struggled a bit.
Thank you so much for looking into this

**Comment by mutalisk999** [comment]
@TheKingKerellos Fixed in #5, you can check out it.
Have a nice day.

**Comment by TheKingKerellos** [comment]
Thanks! I'll be sure to take a look and get back to you

**Comment by TheKingKerellos** [comment]
All working and the dependencies listed for Ubuntu 18.04 still work on Ubuntu 22.04.3 and I was able to build the stratum and run it.
Thanks for your effort
